node-lightning/node-lightning

packages/lntools-graph/__tests__/graph-manager.spec.js, packages/lntools-graph/__tests__/graph.spec.js, packages/lntools-graph/lib/graph-manager.js, packages/lntools-graph/lib/graph.js
Closes #14.
Creates a graph object distinct from the graph-manager that watches for pending messages
=> Graph Refactor

.circleci/config.yml, package.json, packages/lntools-crypto/README.md, packages/lntools-crypto/__tests__/chachapoly.spec.ts, packages/lntools-crypto/__tests__/hkdf.spec.ts, packages/lntools-crypto/lib/hkdf.ts, packages/lntools-crypto/package-lock.json, packages/lntools-crypto/package.json, packages/lntools-noise/README.md, packages/lntools-noise/lib/noise-state.ts, packages/lntools-noise/package-lock.json, packages/lntools-noise/package.json, packages/lntools-wire/package-lock.json, packages/lntools-wire/package.json
Removes dependency on futoin-hkdf.  
Release crypto 0.6.0
Release noise 0.10.0 with updated crypto.
Release wire 0.11.0 with updated noise and crypto.
=> Implement native HKDF 

packages/lntools-wire/__tests__/gossip/gossip-manager.spec.ts, packages/lntools-wire/lib/gossip/gossip-manager.ts
Gossip mananger loads and emits all messages after validation is performed.
Closes #43
=> Restore all messages

packages/lntools-buffer-cursor/__tests__/index.spec.js, packages/lntools-buffer-cursor/__tests__/index.spec.ts, packages/lntools-buffer-cursor/lib/index.ts, packages/lntools-buffer-cursor/package-lock.json, packages/lntools-buffer-cursor/package.json
=> Remove BN.js from buffer-cursor

packages/lntools-crypto/__tests__/key.spec.ts, packages/lntools-crypto/lib/key.ts, packages/lntools-crypto/package-lock.json, packages/lntools-crypto/package.json, packages/lntools-gossip-rocksdb/package-lock.json
=> Remove BN.js for BigInt in @lntools/crypto

packages/lntools-bitcoin/__tests__/txdecoder/decode-tx.spec.js, packages/lntools-bitcoin/lib/tx-decoder/decode-tx-size.ts, packages/lntools-bitcoin/lib/tx-decoder/decode-tx.ts, packages/lntools-bitcoin/lib/tx-decoder/index-of-witness.ts, packages/lntools-bitcoin/lib/tx.ts, packages/lntools-bitcoin/package-lock.json, packages/lntools-bitcoin/package.json, packages/lntools-chain/lib/commitment-generator.ts, packages/lntools-chain/package-lock.json, packages/lntools-chain/package.json, packages/lntools-graph/__tests__/graph-manager.spec.ts, packages/lntools-graph/lib/channel-settings.ts, packages/lntools-graph/lib/channel.ts, packages/lntools-graph/lib/deserialize/channel-from-json.ts, packages/lntools-graph/lib/deserialize/channel-from-message.ts, packages/lntools-graph/lib/deserialize/channel-settings-from-json.ts, packages/lntools-graph/lib/deserialize/channel-settings-from-message.ts, packages/lntools-graph/lib/node.ts, packages/lntools-graph/package-lock.json, packages/lntools-graph/package.json, packages/lntools-invoice/lib/decoder.ts, packages/lntools-invoice/lib/encode-pico.ts, packages/lntools-invoice/lib/hrp-pico.ts, packages/lntools-invoice/lib/invoice.ts, packages/lntools-invoice/package-lock.json, packages/lntools-invoice/package.json, packages/lntools-noise/package-lock.json
References #38 
Remvoves from bitcoin, chain, graph, and invoice modules.
=> Removes BigInt from a variety of modules

packages/lntools-gossip-rocksdb/package-lock.json, packages/lntools-gossip-rocksdb/package.json, packages/lntools-wire/__tests__/gossip/peer-gossip-synchronizer.spec.ts, packages/lntools-wire/lib/gossip/gossip-manager.ts, packages/lntools-wire/lib/gossip/peer-gossip-synchronizer.ts
=> wire: separate states for gossip queries

examples/graph/index.ts, packages/lntools-wire/__tests__/gossip/gossip-manager.spec.ts, packages/lntools-wire/__tests__/peer.spec.ts, packages/lntools-wire/__tests__/pingpong-state.spec.ts, packages/lntools-wire/lib/gossip/gossip-manager.ts, packages/lntools-wire/lib/peer-state.ts, packages/lntools-wire/lib/peer.ts, packages/lntools-wire/lib/pingpong-state.ts
=> wire: implements peer reconnection

packages/lntools-gossip-rocksdb/__tests__/rocksdb-gossip-store.spec.ts, packages/lntools-gossip-rocksdb/__tests__/rocksdb.ts, packages/lntools-gossip-rocksdb/lib/rocksdb-base.ts
=> rocksdb-gossip: allow nested path to be supplied

packages/lntools-gossip-rocksdb/__tests__/rocksdb-gossip-store.spec.ts, packages/lntools-gossip-rocksdb/lib/rocksdb-gossip-store.ts, packages/lntools-wire/__tests__/gossip/gossip-manager.spec.ts, packages/lntools-wire/__tests__/gossip/gossip-memory-store.spec.ts, packages/lntools-wire/lib/gossip/gossip-manager.ts, packages/lntools-wire/lib/gossip/gossip-memory-store.ts, packages/lntools-wire/lib/gossip/gossip-store.ts
=> Restore all node_ann messages on start

examples/graph/index.ts, packages/lntools-wire/__tests__/gossip/gossip-manager.spec.ts, packages/lntools-wire/lib/gossip/gossip-manager.ts
* adds function
* cleans up example
Closes #66
=> Add removeChannelByOutpoint to GossipManager

packages/lntools-wire/__tests__/messages/tlv/extended-channel-announcement-capacity.spec.ts, packages/lntools-wire/__tests__/serialize/tlv-stream-writer.spec.ts, packages/lntools-wire/__tests__/serialize/tlv-value-reader.spec.ts, packages/lntools-wire/__tests__/serialize/tlv-value-writer.spec.ts, packages/lntools-wire/lib/serialize/tlv-value-reader.ts, packages/lntools-wire/lib/serialize/tlv-value-writer.ts
* fixes TlvValueWriter for TUInt64 on split byte values
* adds test
Closes #76
=> Fixing ext_chan_ann capacity TLV

examples/graph/index.ts, packages/lntools-wire/__tests__/gossip/gossip-filter.spec.ts, packages/lntools-wire/lib/gossip/gossip-filter.ts, packages/lntools-wire/lib/gossip/gossip-manager.ts
=> Change full_historical_sync to start at block 0

examples/gossip/index.ts, examples/graph/index.ts, examples/peer/index.ts, packages/wire/__tests__/BitField.spec.ts, packages/wire/__tests__/Peer.spec.ts, packages/wire/__tests__/PeerServer.spec.ts, packages/wire/__tests__/messages/InitMessage.spec.ts, packages/wire/lib/BitField.ts, packages/wire/lib/Peer.ts, packages/wire/lib/PeerServer.ts, packages/wire/lib/flags/InitFeatureFlags.ts, packages/wire/lib/gossip/PeerGossipReceiver.ts, packages/wire/lib/messages/InitMessage.ts
- merge global and local features together
- add TLV support
- disconnect peer when chain_hash is not supported
Closes #22
=> Modify InitMessage to conform to BOLT1 changes

packages/checksum/README.md, packages/checksum/__tests__/crc32c.spec.ts, packages/checksum/lib/crc32c.ts, packages/checksum/lib/index.ts, packages/checksum/package.json, packages/checksum/tsconfig.json, packages/wire/lib/domain/Checksum.ts, packages/wire/package.json
=> Implements CRC32C checksum

packages/wire/__tests__/_test-utils.ts, packages/wire/__tests__/gossip/GossipManager.spec.ts, packages/wire/__tests__/gossip/GossipRelay.spec.ts, packages/wire/lib/gossip/GossipManager.ts, packages/wire/lib/gossip/GossipRelay.ts, packages/wire/lib/index.ts
Adds the `GossipRelay` class that manages relay across all peers.
Closes #99
=> Implements rudimentary GossipRelay

packages/wire/__tests__/gossip/ChannelRangeQuery.spec.ts, packages/wire/__tests__/gossip/ChannelsQuery.spec.ts, packages/wire/lib/Peer.ts, packages/wire/lib/gossip/ChannelRangeQuery.ts, packages/wire/lib/gossip/ChannelsQuery.ts, packages/wire/lib/gossip/GossipManager.ts, packages/wire/lib/gossip/GossipPeer.ts, packages/wire/lib/gossip/GossipQueriesSync.ts
=> Fixes connection failures on QueryChannelRange

packages/wire/__tests__/gossip/ChannelRangeQuery.spec.ts, packages/wire/lib/gossip/ChannelRangeQuery.ts
=> Ease detection of LND reply_channel_range

packages/wire/__tests__/messages/OpenChannelMessage.spec.ts, packages/wire/lib/MessageFactory.ts, packages/wire/lib/MessageType.ts, packages/wire/lib/flags/OpenChannelFlags.ts, packages/wire/lib/index.ts, packages/wire/lib/messages/OpenChannelMessage.ts
Adds type and implements codec.
Closes #110
=> Implement open_channel message

packages/wire/__tests__/messages/AcceptChannelMessage.spec.ts, packages/wire/__tests__/messages/OpenChannelMessage.spec.ts, packages/wire/lib/MessageFactory.ts, packages/wire/lib/MessageType.ts, packages/wire/lib/messages/AcceptChannelMessage.ts
=> Add accept_channel message

packages/core/__tests__/lightning/CommitmentNumber.spec.ts, packages/core/__tests__/lightning/ScriptFactory.spec.ts, packages/core/__tests__/lightning/TxFactory.spec.ts, packages/core/lib/lightning/CommitmentNumber.ts, packages/core/lib/lightning/Htlc.ts, packages/core/lib/lightning/HtlcDirection.ts, packages/core/lib/lightning/ScriptFactory.ts, packages/core/lib/lightning/TxFactory.ts, packages/core/package.json
This encompasses a large portion of BOLT3 transaction construction logic and builds off the TxBuilder in the bitcoin library. Building/signing commitment transactions is a prerequisite to address #112
=> core: utilities for commitment transaction construction

packages/wire/__tests__/messages/FundingCreatedMessage.spec.ts, packages/wire/lib/MessageType.ts, packages/wire/lib/messages/FundingCreatedMessage.ts
Creates the type, serializer, deserializer, and tests.
Closes #112
=> wire: create FundingCreatedMessage type

packages/core/__tests__/ChannelId.spec.ts, packages/core/lib/ChannelId.ts, packages/core/lib/index.ts, packages/wire/__tests__/messages/FundingSignedMessage.spec.ts, packages/wire/lib/MessageType.ts, packages/wire/lib/messages/FundingCreatedMessage.ts, packages/wire/lib/messages/FundingSignedMessage.ts
=> Create funding_signed message primitive

packages/wire/__tests__/messages/FundingLockedMessage.spec.ts, packages/wire/lib/MessageType.ts, packages/wire/lib/messages/FundingLockedMessage.ts
Create class and wire serialization and deserialization methods.
Closes #114
=> wire: create funding_locked message type

packages/noise/lib/noise-socket-options.ts, packages/noise/lib/noise-socket.ts, packages/wire/__tests__/Peer.spec.ts, packages/wire/__tests__/_test-utils.ts, packages/wire/__tests__/gossip/GossipManager.spec.ts, packages/wire/__tests__/gossip/GossipPeer.spec.ts, packages/wire/lib/Peer.ts, packages/wire/lib/gossip/GossipManager.ts, packages/wire/lib/gossip/GossipPeer.ts
Converts streams to Readable so and manually reads from the stream in paused mode instead of relying on pipiong.
Closes #198
=> Fixes reconnection breaking stream piping

lerna.json, packages/bitcoin/package.json, packages/bitcoind/package-lock.json, packages/bitcoind/package.json, packages/bufio/package.json, packages/chainmon/__tests__/BlockWatcher.spec.ts, packages/chainmon/__tests__/TxWatcher.spec.ts, packages/chainmon/lib/TxWatcher.ts, packages/chainmon/package.json, packages/checksum/package.json, packages/core/package.json, packages/crypto/package-lock.json, packages/crypto/package.json, packages/gossip-rocksdb/package-lock.json, packages/gossip-rocksdb/package.json, packages/graph/package.json, packages/invoice/package-lock.json, packages/invoice/package.json, packages/logger/package.json, packages/noise/package.json, packages/onion/package.json, packages/wire/package.json
Catch Tx parse errors and emit the underlying buffer.
=> chainmon: add error handling to chainmon

packages/bitcoin/__tests__/HdKeys.spec.ts, packages/bitcoin/__tests__/HdPrivateKey.spec.ts, packages/bitcoin/lib/HdKeyCodec.ts, packages/bitcoin/lib/HdKeyType.ts, packages/bitcoin/lib/HdPrivateKey.ts, packages/bitcoin/lib/HdPublicKey.ts, packages/bitcoin/lib/Network.ts
=> Implements zpub/prv in HdKeys

packages/bitcoin/__tests__/HdPrivateKey.spec.ts, packages/bitcoin/__tests__/PrivateKey.spec.ts, packages/bitcoin/__tests__/Wif.spec.ts, packages/bitcoin/lib/BitcoinError.ts, packages/bitcoin/lib/BitcoinErrorCode.ts, packages/bitcoin/lib/HdPrivateKey.ts, packages/bitcoin/lib/Network.ts, packages/bitcoin/lib/PrivateKey.ts, packages/bitcoin/lib/Wif.ts
=> Add WIF encoding to PrivateKey and HdPrivateKey

packages/bitcoin/__tests__/Address.spec.ts, packages/bitcoin/__tests__/PrivateKey.spec.ts, packages/bitcoin/__tests__/PublicKey.spec.ts, packages/bitcoin/__tests__/Wif.spec.ts, packages/bitcoin/lib/Address.ts, packages/bitcoin/lib/HdKeyCodec.ts, packages/bitcoin/lib/HdPrivateKey.ts, packages/bitcoin/lib/HdPublicKey.ts, packages/bitcoin/lib/PrivateKey.ts, packages/bitcoin/lib/PublicKey.ts, packages/bitcoin/lib/Wif.ts
Just some improvements based on conversations with @coretechs
=> Refactors of WIF and PublicKey address creation

packages/bitcoin/__tests__/HdPrivateKey.spec.ts, packages/bitcoin/__tests__/HdPublicKey.spec.ts, packages/bitcoin/lib/HdPublicKey.ts
Derive was not using sha512 resulting invalid derivation.
=> bitcoin: fix HdPubKey derive

packages/bitcoin/__tests__/Bits.spec.ts, packages/bitcoin/lib/Bits.ts, packages/bufio/__tests__/BufferReader.spec.ts, packages/bufio/lib/BufferReader.ts
* Adds helper methods to BufferReader for reading variable length ints
* Creates the Bits type
Closes #256 
Prereq for #247
=> Creates `Bits` type

examples/channel/Wallet.ts, examples/channel/index.ts, examples/channel/package.json, packages/bitcoind/lib/BitcoindClient.ts, packages/lightning/__tests__/_test-utils.ts, packages/lightning/lib/channels/IChannelWallet.ts
=> Example implementation of `IChannelWallet` using bitcoind

docs/routines/createErrorMessage.md, packages/lightning/__tests__/_test-utils.ts, packages/lightning/__tests__/channels/Channel.spec.ts, packages/lightning/__tests__/channels/Helpers.spec.ts, packages/lightning/lib/channels/Helpers.ts
=> lightning: implement createErrorMessage

packages/lightning/__tests__/channels/ChannelManager.spec.ts, packages/lightning/__tests__/channels/TransitionFactory.spec.ts, packages/lightning/lib/channels/ChannelManager.ts, packages/lightning/lib/channels/StateMachineFactory.ts, packages/lightning/lib/channels/TransitionFactory.ts
Creates the initialing and funding sub-states
Closes #307
=> lightning: splits opening state

packages/lightning/__tests__/channels/TransitionFactory.spec.ts, packages/lightning/lib/channels/ChannelEvent.ts, packages/lightning/lib/channels/ChannelManager.ts, packages/lightning/lib/channels/IStateMachine.ts, packages/lightning/lib/channels/StateMachine.ts, packages/lightning/lib/channels/TransitionFactory.ts, packages/lightning/lib/channels/TransitionFn.ts, packages/lightning/lib/channels/TransitionResult.ts
Closes #312 
Generic states will just make the code more complicated.
=> Changes to state machine 

packages/lightning/__tests__/_test-utils.ts, packages/lightning/__tests__/channels/StateMachine.spec.ts, packages/lightning/lib/channels/IStateMachine.ts, packages/lightning/lib/channels/StateMachine.ts
=> lightning: add hierarchical processing of states

examples/channel/index.ts, packages/lightning/__tests__/channels/StateMachine.spec.ts, packages/lightning/__tests__/channels/TransitionFactory.spec.ts, packages/lightning/lib/channels/StateMachine.ts, packages/lightning/lib/channels/StateMachineFactory.ts, packages/lightning/lib/channels/TransitionFactory.ts
=> lightning: adds confirm stage to state machine
