node-lightning/node-lightning

packages/lntools-wire/__tests__/gossip/peer-gossip-synchronizer.spec.ts
packages/lntools-wire/lib/gossip/peer-gossip-synchronizer.ts
packages/lntools-wire/package-lock.json
packages/lntools-wire/package.json

Fixes #41 
This change modifies the `PeerGossipSynchronizer` to subtract the start block number from uint32 max value.  
This change max be reverted once all peers correctly handle sending of data.

Fixes query_channel_range remote overflow problem

---

.gitignore
examples/graph/index.ts

This change persists the in-memory graph into the file system under graph.json.
The file graph.json is also added to the .gitignore file
Closes #53

graph-example: periodically persist graph to file

---

examples/gossip/index.ts
examples/gossip/package.json
packages/lntools-wire/__tests__/gossip/gossip-manager.spec.ts
packages/lntools-wire/lib/gossip/gossip-manager.ts

Closes #62 
This commit fixes the gossip_manager so that it will correctly fetch missing
data from a peer when a reconnection event occurs. Prior to this commit it
would use the block height obtained during the initial sync with the peer.
This commit modifies the gossip_manager to perform two actions:
1. It now tracks the highest chan_ann messages block height
2. It corrects an issue where subsequent reconnection events triggered a sync
based on the originating (closure scoped) block height that was obtained
from the gossip store.

wire: gossip_manager tracks last seen block

---

packages/lntools-graph/__tests__/serializers/lnd-serializer.spec.ts
packages/lntools-graph/lib/graph.ts
packages/lntools-graph/lib/serializers/lnd-serializer.ts

This change fixes an issue with the use of `channels` instead of `edges` and
is now inline with the LNDs describeGraph API call.
This change also modifies the serializer to include two methods for serialization
`toObject` will construct the object while `toJSON` will convert the graph object
into a string.
Closes #68 and #69

graph: modifies LndSerializer to more closely align with describeGraph

---

packages/lntools-graph/__tests__/graph-manager.spec.ts
packages/lntools-graph/lib/graph-manager.ts
packages/lntools-graph/lib/graph.ts

Adding a remove channel by outpoint method. This method can be used when
a transaction watcher finds a spent outpoint that needs to be removed from
the graph.
Closes #67

graph: adding remove channel to graph_manager

---

packages/lntools-bitcoind/lib/bitcoind-client.ts
packages/lntools-bitcoind/lib/wait.ts
packages/lntools-wire/__tests__/gossip/gossip-filter.spec.ts
packages/lntools-wire/__tests__/gossip/gossip-manager.spec.ts
packages/lntools-wire/lib/gossip/gossip-filter-chain-client.ts
packages/lntools-wire/lib/gossip/gossip-manager.ts

This adds a new method to bitcoind client to wait for the chain sync to complete.
This method is added to wire/gossip-manager to prevent the gossip sync from starting until the chain client has successfully synced.
This PR closes #37

Wait for bitcoind sync to complete

---

packages/lntools-wire/__tests__/gossip/peer-gossip-receiver.spec.ts
packages/lntools-wire/__tests__/gossip/peer-gossip-synchronizer.spec.ts
packages/lntools-wire/lib/gossip/gossip-manager.ts
packages/lntools-wire/lib/gossip/peer-gossip-receive-state.ts
packages/lntools-wire/lib/gossip/peer-gossip-receiver.ts
packages/lntools-wire/lib/gossip/peer-gossip-synchronizer.ts
packages/lntools-wire/lib/peer.ts

This code splits code in the PeerGossipSynchronizer to isolate the sync code from the update stream code controlled by gossip_timestamp_filter.  This is the first step towards #36 and #40

Starting refactor for multi-strategy gossip 

---

packages/wire/__tests__/Base32.spec.ts
packages/wire/lib/Base32.ts
packages/wire/lib/deserialize/address/torStringFromBuffer.ts
packages/wire/lib/serialize/address/torStringToBuffer.ts
packages/wire/package-lock.json
packages/wire/package.json

Closes #87
This package was being used for base32 encodings which are now found in the Base32.ts file.

Removes the rfc4648 pacakge from wire

---

examples/gossip/index.ts
examples/gossip/package.json
examples/graph/index.ts
examples/graph/package.json
examples/peer/index.ts
examples/peer/package.json
packages/wire/__tests__/gossip/ChannelRangeQuery.spec.ts
packages/wire/__tests__/gossip/ChannelsQuery.spec.ts
packages/wire/__tests__/gossip/GossipQueriesSync.spec.ts
packages/wire/__tests__/gossip/GossipSyncWatcher.spec.ts
packages/wire/lib/gossip/ChannelRangeQuery.ts
packages/wire/lib/gossip/ChannelsQuery.ts
packages/wire/lib/gossip/GossipPeer.ts
packages/wire/lib/gossip/GossipQueriesSync.ts
packages/wire/lib/gossip/GossipSyncWatcher.ts

Removes direct references to the peer.on("message") events in favor of code orchestration. This is prep work for #144.

gossip: refactor message flow for gossip sync

---

packages/wire/__tests__/messages/ClosingSignedMessage.spec.ts
packages/wire/lib/MessageType.ts
packages/wire/lib/messages/ClosingSignedMessage.ts

[BOLT #2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#closing-negotiation-closing_signed) 
- Parameters are defined according to `closing_signed` in [BOLT #2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#closing-negotiation-closing_signed) 
- Implementation is as per the standards given 
- UT attached for testing
@bmancini55

Closing Signed Message Update wire

---

packages/wire/__tests__/gossip/GossipQueriesSync.spec.ts
packages/wire/lib/gossip/ChannelsQuery.ts

Closes #194
This fixes an error where a large number of scids (65k+) was resulting
in a RangeError: Maximum stack size exceeded. Upon investigation, the
ChannelQuery class takes an array of SCIDs and uses array.push(...scids).
Using push in this manner uses .apply under the covers. Apply uses the
stack.  Therefore the number of items you can push is limited by the
stack size.
The code was changed to use an iterator and push a single element at a
time.  An integration test was added to ensure there are not problems
in the future.

gossip: fixes channel sync for large results

---

packages/wire/__tests__/gossip/GossipPeer.spec.ts
packages/wire/__tests__/gossip/GossipSyncWatcher.spec.ts
packages/wire/lib/gossip/GossipManager.ts
packages/wire/lib/gossip/GossipPeer.ts
packages/wire/lib/gossip/GossipSyncWatcher.ts

Two changes that fix errors breaking the transform streams.  Errors are to be expected during gossip analysis and should not break the message pipeline

gossip: fix stream errors

---

.github/workflows/node.js.yml
packages/graph/__tests__/graph-manager.spec.ts
packages/graph/lib/graph-manager.ts

Modifies the GraphManager to perform a null check on the outpoint to
when a remove is performed.
Fixes #204

graph: add outpoint check on remove from graph

---

examples/peer/index.ts

Typo fix. *It ain't much* meme.

Fix typo in examples/peer/index.ts

---

packages/bitcoin/__tests__/Value.spec.ts
packages/bitcoin/lib/Value.ts

This commit allows these two functions to return `self` so the methods can be used in a fluent style. This simple fix allows for easier math operations such as:
```typescript
const inputValue = Value.fromSats(10000);
const fees = Value.fromSats(255);
const outputValue = Value.zero().add(inputValue).sub(fees);
```
Closes #251

bitcoin: make Value.add/sub fluent

---

packages/bitcoin/__tests__/Bits.spec.ts
packages/bitcoin/__tests__/BlockHeader.spec.ts
packages/bitcoin/lib/Bits.ts
packages/bitcoin/lib/BlockHeader.ts
packages/bufio/__tests__/BufferWriter.spec.ts
packages/bufio/__tests__/UintBytes.spec.ts
packages/bufio/lib/BufferWriter.ts
packages/bufio/lib/UintBytes.ts
packages/bufio/lib/index.ts

Creates the `BlockHeader` type and adds buffer IO methods. Also adds ability to create the Block hash from the header.
Closes #247

bitcoin: craete `BlockHeader` type

---

packages/bitcoin/__tests__/HashValue.spec.ts
packages/bitcoin/__tests__/OutPoint.spec.ts
packages/bitcoin/lib/HashValue.ts
packages/bitcoin/lib/OutPoint.ts

Helpers methods added to `HashValue` and `OutPoint` to test for equality.
Closes #249

bitcoin: create OutPoint eq methods

---

packages/bitcoin/__tests__/TxBuilder.spec.ts
packages/bitcoin/lib/TxBuilder.ts

Modifies sign and signSegwitv0 methods to accept PrivateKey instead of an unverified Buffer.
Closes #252

bitcoin: convert TxBuilder sign methods to use PrivateKey

---

packages/bitcoin/__tests__/Script.spec.ts
packages/bitcoin/lib/Script.ts

Helper decodes an address and constructs the appropriate lock script. This will enable simply output construction based on addresses instead of needing to try decoding and appropriate output construction.
Closes #275

bitcoin: create Script.p2AddrLock helper

---

packages/lightning/__tests__/channels/TransitionFactory.spec.ts
packages/lightning/lib/channels/ChannelManager.ts
packages/lightning/lib/channels/StateMachineFactory.ts
packages/lightning/lib/channels/TransitionFactory.ts

This breaks the single opening state into two substates initializing which closes #297 and funding which closes #298. These new states will have transition logic for disconnects, shutdown, and error messages.

lightning: splits channel.opening into init and funding
